// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH61MmcNbc_TyVTZhMnjnQkk3X_aVye5s',
    appId: '1:726520432814:web:79f9344cdeb7a9251fc53f',
    messagingSenderId: '726520432814',
    projectId: 'pion-app-5f12f',
    authDomain: 'pion-app-5f12f.firebaseapp.com',
    storageBucket: 'pion-app-5f12f.firebasestorage.app',
    measurementId: 'G-M81G7PMGDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQt62E2PN02E8SM0W_soUe0nj7D12Oj4A',
    appId: '1:726520432814:android:dd50170dbd65e6261fc53f',
    messagingSenderId: '726520432814',
    projectId: 'pion-app-5f12f',
    storageBucket: 'pion-app-5f12f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdoA7jMhgPl9xQ2lzWytwmAbi6I1YKFkU',
    appId: '1:726520432814:ios:1f805f6748ae94c61fc53f',
    messagingSenderId: '726520432814',
    projectId: 'pion-app-5f12f',
    storageBucket: 'pion-app-5f12f.firebasestorage.app',
    iosBundleId: 'com.penacode.pion',
  );
}
